/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/shortcut/stories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Stories For User */
        get: operations["list_stories_for_user_api_v1_shortcut_stories_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health Check */
        get: operations["health_check_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** TicketDTO */
        TicketDTO: {
            /** Id */
            id: number;
            /** Title */
            title: string;
            /** App Url */
            app_url?: string | null;
            /** Story Type */
            story_type?: string | null;
            /** Estimate */
            estimate?: number | null;
            /**
             * Labels
             * @default []
             */
            labels: string[];
            /** Workflow Id */
            workflow_id?: number | null;
            /** Workflow State Id */
            workflow_state_id?: number | null;
            /** State Name */
            state_name?: string | null;
            /** State Type */
            state_type?: string | null;
            /** Updated At */
            updated_at?: string | null;
            /** Updated At Readable */
            updated_at_readable?: string | null;
        };
        /** TicketListResponse */
        TicketListResponse: {
            /** Data */
            data: components["schemas"]["TicketDTO"][];
            /** Next */
            next?: string | null;
            /** Total */
            total?: number | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_stories_for_user_api_v1_shortcut_stories_get: {
        parameters: {
            query?: {
                owner?: string;
                page_size?: number;
                /** @description User the `next` value returned by the previous call */
                next?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TicketListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_check_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
